server:
  port: 17000

spring:
  jmx:
    default-domain: pdi-edge-service
  aop:
    proxy-target-class: true

management:
  security:
    enabled: false

---
spring:
  profiles: desa

---
spring:
  profiles: qa

---
spring:
  profiles: uat

---
spring:
  profiles: test

---
spring:
  profiles: prep

---
spring:
  profiles: prod
