server:
  port: 14000

spring:
  jmx:
    default-domain: pdi-timestamp-service
  aop:
    proxy-target-class: true

eureka:
  instance:
    home-page-url: /timestampWS
  client:
    healthcheck:
      enabled: true

management:
  security:
    enabled: false

---
spring:
  profiles: desa

---
spring:
  profiles: qa

---
spring:
  profiles: uat

---
spring:
  profiles: test

---
spring:
  profiles: prep

---
spring:
  profiles: prod
